### ISSUE TITLE
Installation in Travis with Python 2.7

### ISSUE THREAD

**Issue by zakandrewking** [biosustain/swiglpk#27]
I'm having an issue installing swiglpk inside travis in Python 2.7, but it works fine in 3.5 and 3.6. See the failing tests here:

https://travis-ci.org/zakandrewking/escher/builds/263299781

The error is below. I tried recreating it locally (macOS), but everything ran fine. Can you see anything obvious that might be going wrong? Thanks!

```
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-uooetu/swiglpk/setup.py", line 53, in <module>
        copy_glpk_header()
      File "/tmp/pip-build-uooetu/swiglpk/setup.py", line 31, in copy_glpk_header
        glpsol_path = os.path.dirname(subprocess.check_output(['which', 'glpsol']))
      File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 573, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['which', 'glpsol']' returned non-zero exit status 1
    Complete output from command python setup.py egg_info:
    Trying to determine glpk.h location
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-uooetu/swiglpk/setup.py", line 53, in <module>
    
        copy_glpk_header()
    
      File "/tmp/pip-build-uooetu/swiglpk/setup.py", line 31, in copy_glpk_header
    
        glpsol_path = os.path.dirname(subprocess.check_output(['which', 'glpsol']))
    
      File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 573, in check_output
    
        raise CalledProcessError(retcode, cmd, output=output)
    
    subprocess.CalledProcessError: Command '['which', 'glpsol']' returned non-zero exit status 1
```

**Comment by hredestig** [comment]
the reason is that pip there for some reason decides to install the source package but not the wheel, perhaps you can try to include
```
pip install https://pypi.python.org/packages/11/d7/814c4231d1f26153b97c32603b9172a0c5e2a1f4d3227f02f8ecc88e2ba9/swiglpk-1.4.4-cp27-cp27m-manylinux1_i686.whl#md5=022c24cc54b7465a432307d9758a5b6f
```
and one could get a clue why it's not picking the wheel..?

**Comment by Midnighter** [comment]
Also not sure why it does a source install rather than getting wheels. Two options that I see:

1. Add the following line to `before_install`:
    ```
    pip install -U pip setuptools wheel
    ```
2. If it still uses sources then you need:
    ```
    addons:
      apt:
        packages:
        - swig
        - libglpk-dev
        - glpk-utils
    ```

**Comment by zakandrewking** [comment]
Makes sense - thanks! I got it to work by adding:

```
  - pip install -U pip
  - pip install swiglpk --only-binary swiglpk
```
